//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Integracoes.NFSe.WebISSReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nfse.abrasf.org.br", ConfigurationName="WebISSReference.nfse")]
    public interface nfse {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (CancelarNfseRequest) da mensagem CancelarNfseRequest não corresponde ao valor padrão (CancelarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/CancelarNfse", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseResponse CancelarNfse(Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/CancelarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseResponse> CancelarNfseAsync(Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarLoteRpsRequest) da mensagem ConsultarLoteRpsRequest não corresponde ao valor padrão (ConsultarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsResponse ConsultarLoteRps(Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfseServicoPrestadoRequest) da mensagem ConsultarNfseServicoPrestadoRequest não corresponde ao valor padrão (ConsultarNfseServicoPrestado)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoResponse ConsultarNfseServicoPrestado(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfseServicoTomadoRequest) da mensagem ConsultarNfseServicoTomadoRequest não corresponde ao valor padrão (ConsultarNfseServicoTomado)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoResponse ConsultarNfseServicoTomado(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfsePorFaixaRequest) da mensagem ConsultarNfsePorFaixaRequest não corresponde ao valor padrão (ConsultarNfsePorFaixa)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaResponse ConsultarNfsePorFaixa(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfsePorRpsRequest) da mensagem ConsultarNfsePorRpsRequest não corresponde ao valor padrão (ConsultarNfsePorRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (RecepcionarLoteRpsRequest) da mensagem RecepcionarLoteRpsRequest não corresponde ao valor padrão (RecepcionarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsResponse RecepcionarLoteRps(Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (GerarNfseRequest) da mensagem GerarNfseRequest não corresponde ao valor padrão (GerarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/GerarNfse", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.GerarNfseResponse GerarNfse(Alpha.Integracoes.NFSe.WebISSReference.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.GerarNfseResponse> GerarNfseAsync(Alpha.Integracoes.NFSe.WebISSReference.GerarNfseRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (SubstituirNfseRequest) da mensagem SubstituirNfseRequest não corresponde ao valor padrão (SubstituirNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseResponse SubstituirNfse(Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseResponse> SubstituirNfseAsync(Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (RecepcionarLoteRpsSincronoRequest) da mensagem RecepcionarLoteRpsSincronoRequest não corresponde ao valor padrão (RecepcionarLoteRpsSincrono)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction="*")]
        Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoResponse RecepcionarLoteRpsSincrono(Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction="*")]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public CancelarNfseRequest() {
        }
        
        public CancelarNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public CancelarNfseResponse() {
        }
        
        public CancelarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarLoteRpsRequest() {
        }
        
        public ConsultarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponse() {
        }
        
        public ConsultarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoPrestadoRequest() {
        }
        
        public ConsultarNfseServicoPrestadoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoPrestadoResponse() {
        }
        
        public ConsultarNfseServicoPrestadoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoTomadoRequest() {
        }
        
        public ConsultarNfseServicoTomadoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoTomadoResponse() {
        }
        
        public ConsultarNfseServicoTomadoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorFaixaRequest() {
        }
        
        public ConsultarNfsePorFaixaRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorFaixaResponse() {
        }
        
        public ConsultarNfsePorFaixaResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorRpsRequest() {
        }
        
        public ConsultarNfsePorRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponse() {
        }
        
        public ConsultarNfsePorRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsRequest() {
        }
        
        public RecepcionarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponse() {
        }
        
        public RecepcionarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public GerarNfseRequest() {
        }
        
        public GerarNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public GerarNfseResponse() {
        }
        
        public GerarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public SubstituirNfseRequest() {
        }
        
        public SubstituirNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public SubstituirNfseResponse() {
        }
        
        public SubstituirNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincronoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsSincronoRequest() {
        }
        
        public RecepcionarLoteRpsSincronoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincronoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsSincronoResponse() {
        }
        
        public RecepcionarLoteRpsSincronoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface nfseChannel : Alpha.Integracoes.NFSe.WebISSReference.nfse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class nfseClient : System.ServiceModel.ClientBase<Alpha.Integracoes.NFSe.WebISSReference.nfse>, Alpha.Integracoes.NFSe.WebISSReference.nfse {
        
        public nfseClient() {
        }
        
        public nfseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public nfseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public nfseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public nfseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.CancelarNfse(Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseRequest request) {
            return base.Channel.CancelarNfse(request);
        }
        
        public string CancelarNfse(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).CancelarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.CancelarNfseAsync(Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseRequest request) {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseResponse> CancelarNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.CancelarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarLoteRps(Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRps(request);
        }
        
        public string ConsultarLoteRps(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarLoteRpsAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarNfseServicoPrestado(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoRequest request) {
            return base.Channel.ConsultarNfseServicoPrestado(request);
        }
        
        public string ConsultarNfseServicoPrestado(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarNfseServicoPrestado(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarNfseServicoPrestadoAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoRequest request) {
            return base.Channel.ConsultarNfseServicoPrestadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoPrestadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarNfseServicoPrestadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarNfseServicoTomado(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoRequest request) {
            return base.Channel.ConsultarNfseServicoTomado(request);
        }
        
        public string ConsultarNfseServicoTomado(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarNfseServicoTomado(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarNfseServicoTomadoAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoRequest request) {
            return base.Channel.ConsultarNfseServicoTomadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfseServicoTomadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarNfseServicoTomadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarNfsePorFaixa(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaRequest request) {
            return base.Channel.ConsultarNfsePorFaixa(request);
        }
        
        public string ConsultarNfsePorFaixa(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarNfsePorFaixa(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarNfsePorFaixaAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaRequest request) {
            return base.Channel.ConsultarNfsePorFaixaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorFaixaRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarNfsePorFaixaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarNfsePorRps(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRps(request);
        }
        
        public string ConsultarNfsePorRps(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarNfsePorRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.ConsultarNfsePorRpsAsync(Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.ConsultarNfsePorRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.RecepcionarLoteRps(Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRps(request);
        }
        
        public string RecepcionarLoteRps(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).RecepcionarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.RecepcionarLoteRpsAsync(Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.GerarNfseResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.GerarNfse(Alpha.Integracoes.NFSe.WebISSReference.GerarNfseRequest request) {
            return base.Channel.GerarNfse(request);
        }
        
        public string GerarNfse(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.GerarNfseRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.GerarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.GerarNfseResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).GerarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.GerarNfseResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.GerarNfseAsync(Alpha.Integracoes.NFSe.WebISSReference.GerarNfseRequest request) {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.GerarNfseResponse> GerarNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.GerarNfseRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.GerarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).GerarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.SubstituirNfse(Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseRequest request) {
            return base.Channel.SubstituirNfse(request);
        }
        
        public string SubstituirNfse(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).SubstituirNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.SubstituirNfseAsync(Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseRequest request) {
            return base.Channel.SubstituirNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseResponse> SubstituirNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.SubstituirNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).SubstituirNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoResponse Alpha.Integracoes.NFSe.WebISSReference.nfse.RecepcionarLoteRpsSincrono(Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoRequest request) {
            return base.Channel.RecepcionarLoteRpsSincrono(request);
        }
        
        public string RecepcionarLoteRpsSincrono(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoResponse retVal = ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).RecepcionarLoteRpsSincrono(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoResponse> Alpha.Integracoes.NFSe.WebISSReference.nfse.RecepcionarLoteRpsSincronoAsync(Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoRequest request) {
            return base.Channel.RecepcionarLoteRpsSincronoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoRequest inValue = new Alpha.Integracoes.NFSe.WebISSReference.RecepcionarLoteRpsSincronoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((Alpha.Integracoes.NFSe.WebISSReference.nfse)(this)).RecepcionarLoteRpsSincronoAsync(inValue);
        }
    }
}
